/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashSet;

/**
 *
 * @author juampy
 */
public class AgregarVehiculoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarVehiculoView.class.getName());

    /**
     * Creates new form AgregarVehiculoView
     */
    MenuPrincipalView menu;
    public AgregarVehiculoView(MenuPrincipalView menu) {
        initComponents();
        configurarEventosYVista(); 
        actualizarTabla();
        this.menu = menu;
        
    }

    // --- LÓGICA DE VISTA DINÁMICA ---
    private void configurarEventosYVista() {
        
        cmpTipoVehiculo.addActionListener(evt -> {
            boolean esCombustible = cmpTipoVehiculo.getSelectedItem().toString().equals("COMBUSTIBLE");
            
            // Campos de Combustible
            cmpKmporlitros.setVisible(esCombustible);
            cmplitrosExtras.setVisible(esCombustible);
            jLabel7.setVisible(esCombustible);
            jLabel8.setVisible(esCombustible);
            
            
            cmpKwhBase.setVisible(!esCombustible); 
            jLabel10.setVisible(!esCombustible);
            
            
            this.revalidate();
            this.repaint();
        });
        
        cmpTipoVehiculo.setSelectedIndex(0); 

        
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
    }

    
    private void actualizarTabla() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {"Patente", "Marca-Modelo-Pais", "Sucursal"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        for (VehiculoViewModel v : Controlador.getVehiculos()) {
            modelo.addRow(new Object[]{
                v.getPatente(),
                v.getVehiculo(),
                v.getSucursal()
            });
        }
        jTable1.setModel(modelo);
    }

    private void limpiarCampos() {
        cmpPatente.setText("");
        cmpModelo.setText("");
        cmpMarca.setText("");
        cmpAnio.setText("");
        cmpCapCarga.setText("");
        cmpKmporlitros.setText("");
        cmplitrosExtras.setText("");
        cmpKwhBase.setText("");
    }

    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("btnEliminar"+evt.getActionCommand());
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un vehículo de la tabla para eliminar.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String patente = jTable1.getValueAt(filaSeleccionada, 0).toString();
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar el vehículo " + patente + "?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            Controlador.eliminarVehiculo(patente);
            actualizarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, "Vehículo eliminado.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmpSucursal = new javax.swing.JComboBox<>();
        cmpPatente = new javax.swing.JTextField();
        cmpAnio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JToggleButton();
        cmpCapCarga = new javax.swing.JTextField();
        cmpKmporlitros = new javax.swing.JTextField();
        cmplitrosExtras = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmpTipoVehiculo = new javax.swing.JComboBox<>();
        cmpKwhBase = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmpModelo = new javax.swing.JTextField();
        cmpMarca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmpPais = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Patente");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Sucursal:");

        jLabel5.setText("Capacidad de carga:");

        cmpSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUC01", "SUC02" }));

        cmpPatente.addActionListener(this::cmpPatenteActionPerformed);

        cmpAnio.addActionListener(this::cmpAnioActionPerformed);

        jLabel6.setText("Añio:");

        jLabel7.setText("Kilometros por litros:");

        jLabel8.setText("Consumo de litros extras:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("INGRESAR VEHICULO");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnEliminar.setText("ELIMINAR");

        cmpCapCarga.setColumns(10);

        cmpKmporlitros.setColumns(10);

        cmplitrosExtras.setColumns(10);

        jLabel11.setText("Tipo de vehiculo:");

        cmpTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMBUSTIBLE", "ELECTRICO" }));

        cmpKwhBase.setColumns(10);

        jLabel10.setText("kwh base:");

        jLabel12.setText("Pais:");

        jButton1.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jButton1.setText("VOLVER");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmpAnio)
                            .addComponent(cmpPais)
                            .addComponent(cmpMarca)
                            .addComponent(cmpModelo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmpSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cmpTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmplitrosExtras)
                            .addComponent(cmpKmporlitros)
                            .addComponent(cmpKwhBase)
                            .addComponent(cmpCapCarga))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 264, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmpPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cmpTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmpKwhBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmpModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmpMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpCapCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmpPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmpKmporlitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(cmplitrosExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmpSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnRegistrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmpPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpPatenteActionPerformed

    private void cmpAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpAnioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            try {
            
            if (cmpPatente.getText().trim().isEmpty() || 
                cmpModelo.getText().trim().isEmpty() || 
                cmpMarca.getText().trim().isEmpty() ||
                cmpAnio.getText().trim().isEmpty() ||
                cmpCapCarga.getText().trim().isEmpty()) {
                
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

        
            String patente = cmpPatente.getText().trim().toUpperCase();
            String modelo = cmpModelo.getText().trim();
            String marcaNombre = cmpMarca.getText().trim();
            String pais=cmpPais.getText().trim();
            int anio = Integer.parseInt(cmpAnio.getText().trim());
            double capCarga = Double.parseDouble(cmpCapCarga.getText().trim());
            int indexSucursal = cmpSucursal.getSelectedIndex();
            
            String tipo = cmpTipoVehiculo.getSelectedItem().toString();
            boolean exito = false;

           
            if (tipo.equals("COMBUSTIBLE")) {
                if(cmpKmporlitros.getText().trim().isEmpty() || cmplitrosExtras.getText().trim().isEmpty()) {
                     javax.swing.JOptionPane.showMessageDialog(this, "Complete los campos específicos de Combustible.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                     return;
                }
                double kmLitro = Double.parseDouble(cmpKmporlitros.getText().trim());
                double litrosExtra = Double.parseDouble(cmplitrosExtras.getText().trim());
                
                exito = Controlador.registrarVehiculoCombustible(patente, marcaNombre, modelo,pais, anio, capCarga, indexSucursal, kmLitro, litrosExtra);
            } else {
                if(cmpKwhBase.getText().trim().isEmpty()) {
                     javax.swing.JOptionPane.showMessageDialog(this, "Complete el campo Kwh Base.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                     return;
                }
                double kwhBase = Double.parseDouble(cmpKwhBase.getText().trim());
                
                exito = Controlador.registrarVehiculoElectrico(patente, marcaNombre, modelo,pais, anio, capCarga, indexSucursal, kwhBase);
            }

            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vehículo registrado exitosamente.");
                actualizarTabla();
                limpiarCampos();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Ya existe un vehículo con esa patente.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
           
            javax.swing.JOptionPane.showMessageDialog(this, "Error de formato: Asegúrese de ingresar números válidos en Año, Capacidad y Consumos.", "Datos inválidos", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
            
           
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        menu.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AgregarVehiculoView().setVisible(true));
    }
    
    public void iniciar(){
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField cmpAnio;
    private javax.swing.JTextField cmpCapCarga;
    private javax.swing.JTextField cmpKmporlitros;
    private javax.swing.JTextField cmpKwhBase;
    private javax.swing.JTextField cmpMarca;
    private javax.swing.JTextField cmpModelo;
    private javax.swing.JTextField cmpPais;
    private javax.swing.JTextField cmpPatente;
    private javax.swing.JComboBox<String> cmpSucursal;
    private javax.swing.JComboBox<String> cmpTipoVehiculo;
    private javax.swing.JTextField cmplitrosExtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
